// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PérezJosé_Progreso1.Data;

#nullable disable

namespace PérezJosé_Progreso1.Migrations
{
    [DbContext(typeof(PérezJosé_Progreso1Context))]
    partial class PérezJosé_Progreso1ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PérezJosé_Progreso1.Models.Celular", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Año")
                        .HasColumnType("int");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PerezJId")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PerezJId")
                        .IsUnique();

                    b.ToTable("Celular");
                });

            modelBuilder.Entity("PérezJosé_Progreso1.Models.PerezJ", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AtributoBool")
                        .HasColumnType("bit");

                    b.Property<decimal>("AtributoDecimal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AtributoInt")
                        .HasColumnType("int");

                    b.Property<string>("AtributoString")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PerezJ");
                });

            modelBuilder.Entity("PérezJosé_Progreso1.Models.Celular", b =>
                {
                    b.HasOne("PérezJosé_Progreso1.Models.PerezJ", "PerezJ")
                        .WithOne("Celular")
                        .HasForeignKey("PérezJosé_Progreso1.Models.Celular", "PerezJId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerezJ");
                });

            modelBuilder.Entity("PérezJosé_Progreso1.Models.PerezJ", b =>
                {
                    b.Navigation("Celular")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
